accounts/urls.py
from django.urls import path

from . import views

app_name="accounts"

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
]

buat_jadwal/urls.py
from django.urls import path
from . import views

app_name = 'buat_jadwal'

urlpatterns = [
    path('', views.buat, name='buat'),
    path('berhasil', views.berhasil, name='berhasil'),
    path('list', views.list_jadwal, name='list'),
    path('delete/', views.delete, name='delete')
]

carijadwal/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'carijadwal'

urlpatterns = [
        # url(r'^add/(?P<add_id>[0-9]+)$', views.add, name='add'),
        # url(r'^delete/(?P<delete_id>[0-9]+)$', views.delete, name='delete'),
        # url(r'^$', HomePageView.as_view(), name='home'),
        # url(r'^search/$', SearchResultsView.as_view(), name='search_results'),
        path('add/<int:add_id>', views.add, name="add"),
        path('', views.HomePageView.as_view(), name="home"),
        path('lihatjadwal', views.lihatjadwal, name="lihatjadwal"),
        path('search/', views.SearchResultsView.as_view(), name="search_results"),

]

tutorq/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.views.generic.base import TemplateView 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('template', views.template),
    
    # for account
    path('accounts/', include('accounts.urls')), 
    path('accounts/', include('django.contrib.auth.urls')), 
    path('', TemplateView.as_view(template_name='accounts/home.html'), name='home'), # new
    path('buatJadwal/', include('buat_jadwal.urls')),
    path('cariJadwal/', include('carijadwal.urls')),
    path('', views.home, name='homepage'),
]

tutorq/views.py
from django.shortcuts import render

def hello(request):
    return render(request, 'hello_world.html')

def template(request):
    return render(request, 'template.html')

def home(request):
    return render(request, 'accounts/home.html')

tutorq/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>{{ title }}</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% block style %}
    {% endblock style %}
    
  </head>
  
  <body>
    <div class="container">
      {% block content %}
      
      {% endblock content %}
    </div>
    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    {% block scripts %}
    {% endblock scripts %}
  </body>
</html>

tutorq/templates/hello_world.html
<!DOCTYPE>
<html>
  <head>
    <title>HELLO WORLD</title>
  </head>
  <body>
    <h1>Hello World</h1>
  </body>
</html>

tutorq/templates/template.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
  <link href="{% static 'css/template.css' %}" type='text/css' rel='stylesheet'>
  {% block specific_style %}
  {% endblock specific_style %}
{% endblock style %}

{% block content %}
  <nav class="navbar navbar-default">
    <div class="navbar header">
      <img src="{% static 'image 2.png' %}">
    </div>
    <div class="container-fluid">
      <ul class="nav navbar-nav" style="flex-direction: row">
        <li></li>
        {% if not user.is_authenticated %}<li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>{% endif %}
        {% if not user.is_authenticated %}<li><a href="{% url 'login' %}">Log in</a></li>{% endif %}
        {% if user.is_authenticated %}<li><a href="{% url 'carijadwal:home' %}">Cari Jadwal</a></li>{% endif %}
        {% if user.is_authenticated %}<li><a href="{% url 'carijadwal:lihatjadwal' %}">Lihat Jadwal</a></li>{% endif %}
        {% if user.is_authenticated %}<li><a href="{% url 'buat_jadwal:buat' %}">Buat Jadwal</a></li>{% endif %}
        {% if user.is_authenticated %}<li><a href="{% url 'buat_jadwal:list' %}">Jadwalku Buat</a></li>{% endif %}
      </ul>
    </div>
  </nav>
  {% block views %}
  {% endblock views %}
{% endblock content %}