carijadwal/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'carijadwal'

urlpatterns = [
        # url(r'^add/(?P<add_id>[0-9]+)$', views.add, name='add'),
        # url(r'^delete/(?P<delete_id>[0-9]+)$', views.delete, name='delete'),
        # url(r'^$', HomePageView.as_view(), name='home'),
        # url(r'^search/$', SearchResultsView.as_view(), name='search_results'),
        path('add/<int:add_id>', views.add, name="add"),
        path('', views.HomePageView.as_view(), name="home"),
        path('lihatjadwal', views.lihatjadwal, name="lihatjadwal"),
        path('search/', views.SearchResultsView.as_view(), name="search_results"),

]

tutorq/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.views.generic.base import TemplateView 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('template', views.template),
    
    # for account
    path('accounts/', include('accounts.urls')), 
    path('accounts/', include('django.contrib.auth.urls')), 
    path('', TemplateView.as_view(template_name='accounts/home.html'), name='home'), # new
    path('buatJadwal/', include('buat_jadwal.urls')),
    path('cariJadwal/', include('carijadwal.urls')),
    path('', views.home, name='homepage'),
]

carijadwal/models.py
from django.db import models
from django.contrib.auth import get_user_model
from buat_jadwal.models import Jadwal
# Create your models here.


class RelasiJadwal(models.Model):

    tutee = models.ForeignKey(
	    get_user_model(),
	    on_delete=models.CASCADE,
	    null=True,
	    blank=True,
        )
    
    jadwal = models.ForeignKey(
	    Jadwal,
	    on_delete=models.CASCADE,
	    null=True,
	    blank=True,
        )

	

carijadwal/forms.py
from django import forms

class SearchForm(forms.ModelForm):
	class Meta:
		matkul = forms.CharField(max_length=50)
		hari = forms.CharField(max_length=50)

carijadwal/views.py
from django.shortcuts import render, redirect
from .models import RelasiJadwal
from .forms import SearchForm
from django.views.generic import TemplateView, ListView
from django.db.models import Q
from buat_jadwal.models import Jadwal


def add(request, add_id):
        tutee_add = request.user;
        jadwal_add = Jadwal.objects.get(id=add_id)

        relasi = RelasiJadwal(tutee=tutee_add, jadwal=jadwal_add)
        relasi.save()
                
        #jadwal_form = JadwalForm(request.POST or None, initial=ubah, instance=jadwal_change)
        #jadwal_form.save()

        return render(request, 'carijadwal/home.html')
def delete(request, delete_id):
        pass

        #return render(request, 'home.html')

def lihatjadwal(request):
        model = Jadwal
        template_name = 'carijadwal/list.html'
        relasi_relasi = RelasiJadwal.objects.filter(tutee=request.user)
        object_list = []

        for relasi in relasi_relasi:
            r = Jadwal.objects.get(pk=relasi.jadwal.id)
            if(r not in object_list): object_list.append(r)
        
        context = {'object_list': object_list}
        return render(request, template_name, context)
        

# def home(request):
#     if request.method == 'POST':
#         form = ContactForm(request.POST)
#         if form.is_valid():
#             pass  # does nothing, just trigger the validation
#     else:
#         form = ContactForm()
#     return render(request, 'search.html', {'form': form})

class HomePageView(TemplateView):
    template_name = 'carijadwal/home.html'

class SearchResultsView(ListView):
    model = Jadwal
    template_name = 'carijadwal/search_results.html'

    def get_queryset(self):
        query1 = self.request.GET.get('q1')
        query2 = self.request.GET.get('q2')
        object_list = Jadwal.objects.filter(
            Q(matkul__icontains=query1) & Q(hari__icontains=query2)
        )
        return object_list

carijadwal/templates/carijadwal/home.html
{% extends "template.html"%}

{% block views %}
<h1 style="text-align:center; padding:5%;"> Cari Jadwal </h1>
<form action="{% url 'carijadwal:search_results' %}" method="get">
	<!-- Search form -->
	<div class="active-purple-3 active-purple-4 mb-4">
	  <input name = "q1" class="form-control" type="text" placeholder="Cari jadwal berdasarkan matkul" aria-label="Search">
	</div>
	<!-- Search form -->
	<div class="active-cyan-3 active-cyan-4 mb-4">
	  <input name = "q2" class="form-control" type="text" placeholder="Cari jadwal berdasarkan hari" aria-label="Search">
	</div>
	<button type="submit" class="btn btn-primary">Cari jadwal</button>
</form>
<div>
{% endblock views %}

carijadwal/templates/carijadwal/list.html
{% extends "template.html"%}

{% block views %}
	<h1 style="text-align:center; padding:5%;"> Lihat Jadwal </h1>
		  	<table class="table">
		  <thead>
		    <tr>
		      <th scope="col">#</th>
		      <th scope="col">Matkul</th>
		      <th scope="col">Hari</th>
		      <th scope="col">Jam Mulai</th>
		      <th scope="col">Jam Selesai</th>
		    </tr>
		  </thead>
		  <tbody>
		  	{% for jadwal in object_list%}
			    <tr>
			      <th scope="row">{{forloop.counter}}</th>
				  <td>{{jadwal.matkul}}</td>
				  <td>{{jadwal.hari}}</td>
				  <td>{{jadwal.jam_mulai}}</td>
				  <td>{{jadwal.jam_selesai}}</td>
				 
			    </tr>
		    {% endfor %}

  </tbody>
{% endblock views %}

carijadwal/templates/carijadwal/search_results.html
{% extends "template.html"%}

{% block views %}
	<h1 style="text-align:center; padding:5%;"> Hasil Pencarian </h1>

		  	<table class="table">
		  <thead>
		    <tr>
		      <th scope="col">#</th>
		      <th scope="col">Matkul</th>
		      <th scope="col">Hari</th>
		      <th scope="col">Jam Mulai</th>
		      <th scope="col">Jam Selesai</th>
			  <th scope="col">Menambahkan Jadwal</th>
		    </tr>
		  </thead>
		  <tbody>
		  	{% for jadwal in object_list%}
			    <tr>
			      <th scope="row">{{forloop.counter}}</th>
				  <td>{{jadwal.matkul}}</td>
				  <td>{{jadwal.hari}}</td>
				  <td>{{jadwal.jam_mulai}}</td>
				  <td>{{jadwal.jam_selesai}}</td>
				  <td> <a class="btn btn-primary" href="{% url 'carijadwal:add' jadwal.id%}"> Tambahkan </a>
			    </tr>
		    {% endfor %}

  </tbody>
{% endblock views %}